name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Build application
        run: make -f MakeFile

      - name: Build test
        run: make -f MakeFile test

      - name: Run test
        run: ./bin/test.bin < ../test/test_data.csv